### ISSUE TITLE
ngv_box3dpolygon unknown function in PostgreSQL

### ISSUE THREAD

**Issue by racinmat** [umautobots/gta-postprocessing#1]
[Here](https://github.com/umautobots/gta-postprocessing/blob/master/generate_bboxes.py#L271) you are using `ngv_box3dpolygon` function in the PostgreSQL. Since I can not find it anywhere in PostgreSQL, nor in PostGis extension, I guess it is your function. 
Could you add your defined functions in the PostgreSQL database?

**Comment by muaz-git** [comment]
@racinmat were you successful in finding the solution to it?

**Comment by racinmat** [comment]
@muaz-git no,still nothing. I also wrote e-mail to barcharcraz, but got no answer.
And I haven't try to guess how could this implementation look like.
@barcharcraz how is it going with releasing stored procedures?

**Comment by Cuky88** [comment]
@barcharcraz Are any news here?

**Comment by racinmat** [comment]
Great, SQL schema is now here, thanks much, @barcharcraz ! 
https://github.com/umautobots/gta-postprocessing/blob/master/schema.sql
